-- =============================================================================
-- IRISAI STUDIO — SUPABASE POSTGRESQL SCHEMA DEFINITION
-- CHECKPOINT 2: EXACT REPLICATION OF SQL SERVER HMNC_PRO SCHEMA
-- Compatible with SQLAlchemy ORM (backend/database/models.py)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Table: "Users"
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Users" (
    "UserID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username" VARCHAR(100) NOT NULL,
    "PasswordHash" VARCHAR(255) NOT NULL,
    "Role" VARCHAR(20) NOT NULL DEFAULT 'USER',
    "Status" VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "LastLogin" TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT "UQ_Users_Username" UNIQUE ("Username"),
    CONSTRAINT "CK_Users_Role" CHECK (UPPER("Role") IN ('ADMIN', 'USER')),
    CONSTRAINT "CK_Users_Status" CHECK (UPPER("Status") IN ('ACTIVE', 'INACTIVE'))
);

-- -----------------------------------------------------------------------------
-- 2. Table: "Predictions"
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Predictions" (
    "PredictionID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserID" INTEGER NOT NULL,
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "SepalLength" DOUBLE PRECISION NOT NULL,
    "SepalWidth" DOUBLE PRECISION NOT NULL,
    "PetalLength" DOUBLE PRECISION NOT NULL,
    "PetalWidth" DOUBLE PRECISION NOT NULL,
    "PredictedSpecies" VARCHAR(50) NOT NULL,
    "ProbabilitySetosa" DOUBLE PRECISION NULL,
    "ProbabilityVersicolor" DOUBLE PRECISION NULL,
    "ProbabilityVirginica" DOUBLE PRECISION NULL,
    "ModelName" VARCHAR(100) NULL,
    "Kernel" VARCHAR(20) NULL,
    CONSTRAINT "FK_Predictions_Users" FOREIGN KEY ("UserID")
        REFERENCES "Users" ("UserID") ON DELETE RESTRICT,
    CONSTRAINT "CK_Predictions_Kernel" CHECK (
        "Kernel" IS NULL OR UPPER("Kernel") IN ('MLP', 'SIGMOID', 'POLY', 'LINEAR', 'RBF')
    )
);

CREATE INDEX IF NOT EXISTS "IX_Predictions_UserID" ON "Predictions" ("UserID");

-- -----------------------------------------------------------------------------
-- 3. Table: "ModelHistory"
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "ModelHistory" (
    "ModelID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ModelName" VARCHAR(100) NOT NULL,
    "Kernel" VARCHAR(20) NOT NULL,
    "Accuracy" DOUBLE PRECISION NULL,
    "PrecisionScore" DOUBLE PRECISION NULL,
    "RecallScore" DOUBLE PRECISION NULL,
    "F1Score" DOUBLE PRECISION NULL,
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CK_ModelHistory_Kernel" CHECK (
        UPPER("Kernel") IN ('MLP', 'SIGMOID', 'POLY', 'LINEAR', 'RBF')
    )
);

-- -----------------------------------------------------------------------------
-- 4. Table: "KernelUsageHistory"
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "KernelUsageHistory" (
    "UsageID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserID" INTEGER NOT NULL,
    "Kernel" VARCHAR(20) NOT NULL,
    "UsedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_KernelUsage_Users" FOREIGN KEY ("UserID")
        REFERENCES "Users" ("UserID") ON DELETE RESTRICT,
    CONSTRAINT "CK_KernelUsage_Kernel" CHECK (
        UPPER("Kernel") IN ('MLP', 'SIGMOID', 'POLY', 'LINEAR', 'RBF')
    )
);

CREATE INDEX IF NOT EXISTS "IX_KernelUsage_UserID" ON "KernelUsageHistory" ("UserID");
